spring.application.name=demo
spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.main.web-application-type=none

#spring.ai.openai.chat.options.model=gpt-5-mini
#spring.ai.openai.chat.options.n=1
#spring.ai.openai.chat.options.top-p=1.0
#spring.ai.openai.chat.options.max-completion-tokens=2048
#spring.ai.openai.chat.options.temperature=1.0
#spring.ai.openai.chat.options.service-tier=flex
#spring.ai.openai.chat.options.reasoning-effort=low